import json
import logging
from datetime import datetime, timezone
from xml.etree import ElementTree as ET

import httpx

from app.config import settings

logger = logging.getLogger(__name__)

XWIKI_REST = f"{settings.xwiki_url}/rest"
WARNING_HEADER = (
    "{{warning}}\n"
    "This page is auto-generated by AutoDoc. "
    "Manual edits will be overwritten on next scan.\n"
    "{{/warning}}\n\n"
)


def _auth() -> tuple[str, str]:
    return (settings.xwiki_admin_user, settings.xwiki_admin_password)


def _build_page_xml(title: str, content: str) -> bytes:
    page = ET.Element("page", xmlns="http://www.xwiki.org")
    ET.SubElement(page, "title").text = title
    ET.SubElement(page, "syntax").text = "xwiki/2.1"
    ET.SubElement(page, "content").text = content
    return ET.tostring(page, encoding="unicode").encode("utf-8")


async def write_scan_result(scan_type: str, page_name: str, title: str,
                            data: dict, analysis: str | None = None):
    """Write scan results as an XWiki page under AutoDoc/ space."""
    content_lines = [
        WARNING_HEADER,
        f"= {title} =",
        "",
        f"**Scan type:** {scan_type}",
        f"**Scan time:** {data.get('scan_time', datetime.now(timezone.utc).isoformat())}",
        "",
    ]

    if analysis:
        content_lines.extend([
            "== AI Analysis ==",
            "",
            analysis,
            "",
        ])

    content_lines.extend([
        "== Raw Data ==",
        "",
        "{{code language='json'}}",
        json.dumps(data, indent=2, default=str),
        "{{/code}}",
    ])

    content = "\n".join(content_lines)
    xml_body = _build_page_xml(title, content)

    url = f"{XWIKI_REST}/wikis/xwiki/spaces/AutoDoc/pages/{page_name}"
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.put(
            url,
            auth=_auth(),
            content=xml_body,
            headers={"Content-Type": "application/xml"},
        )
        resp.raise_for_status()

    logger.info("Wrote AutoDoc page: AutoDoc/%s", page_name)


async def write_docker_scan(data: dict, analysis: str | None = None):
    """Write Docker scan results."""
    title = f"Docker - {data.get('host', {}).get('hostname', 'unknown')}"

    # Build structured content
    lines = [
        WARNING_HEADER,
        f"= {title} =",
        "",
        f"**Host:** {data.get('host', {}).get('hostname', '')}",
        f"**Docker Version:** {data.get('host', {}).get('docker_version', '')}",
        f"**OS:** {data.get('host', {}).get('os', '')}",
        f"**CPUs:** {data.get('host', {}).get('cpus', '')}",
        f"**Memory:** {data.get('host', {}).get('memory_gb', '')} GB",
        f"**Scan time:** {data.get('scan_time', '')}",
        "",
        "== Containers ==",
        "",
        "|=Name|=Image|=Status|=Ports",
    ]

    for c in data.get("containers", []):
        ports_str = ", ".join(
            f"{k}->{','.join(v)}" for k, v in c.get("ports", {}).items() if v
        ) or "-"
        lines.append(f"|{c['name']}|{c['image']}|{c['status']}|{ports_str}")

    if analysis:
        lines.extend(["", "== AI Analysis ==", "", analysis])

    content = "\n".join(lines)
    xml_body = _build_page_xml(title, content)

    url = f"{XWIKI_REST}/wikis/xwiki/spaces/AutoDoc/pages/Docker"
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.put(
            url, auth=_auth(), content=xml_body,
            headers={"Content-Type": "application/xml"},
        )
        resp.raise_for_status()


async def write_network_scan(data: dict, analysis: str | None = None):
    """Write network scan results."""
    title = "Network Discovery"
    lines = [
        WARNING_HEADER,
        f"= {title} =",
        "",
        f"**Subnets scanned:** {', '.join(data.get('subnets', []))}",
        f"**Hosts found:** {data.get('hosts_found', 0)}",
        f"**Scan time:** {data.get('scan_time', '')}",
        "",
        "== Discovered Hosts ==",
        "",
        "|=IP|=Hostname|=State|=MAC|=Vendor",
    ]

    for h in data.get("hosts", []):
        lines.append(
            f"|{h['ip']}|{h.get('hostname', '')}|{h.get('state', '')}"
            f"|{h.get('mac', '')}|{h.get('vendor', '')}"
        )

    if analysis:
        lines.extend(["", "== AI Analysis ==", "", analysis])

    content = "\n".join(lines)
    xml_body = _build_page_xml(title, content)

    url = f"{XWIKI_REST}/wikis/xwiki/spaces/AutoDoc/pages/Network"
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.put(
            url, auth=_auth(), content=xml_body,
            headers={"Content-Type": "application/xml"},
        )
        resp.raise_for_status()
